#pragma once

#define VA_START (0xffff000000000000)

#define BOARD_BASE (0x3F00000)
#define PHY_BASE   (VA_START + BOARD_BASE)

#define PHYS_MEM_SIZE (0x40000000)


#define PAGE_MASK 0xfffffffffffff000
#define PAGE_SHIFT 12
#define TABLE_SHIFT 9
#define SECTION_SHIFT (PAGE_SHIFT + TABLE_SHIFT)

#define PAGE_SIZE (1 << PAGE_SHIFT)
#define SECTION_SIZE (1 << SECTION_SHIFT)

#define LOW_MEMORY (2 * SECTION_SIZE)
#define HIGH_MEMORY BOARD_BASE

#define PAGING_MEMORY (HIGH_MEMORY - LOW_MEMORY)
#define PAGING_PAGES (PAGING_MEMORY / PAGE_SIZE)

#if 0
#define PTRS_PER_TABLE (1 << TABLE_SHIFT)

#define PGD_SHIFT PAGE_SHIFT + 3 * TABLE_SHIFT
#define PUD_SHIFT PAGE_SHIFT + 2 * TABLE_SHIFT
#define PMD_SHIFT PAGE_SHIFT + TABLE_SHIFT

#define PG_DIR_SIZE (3 * PAGE_SIZE)
#endif
